// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ProcessedDonatesColumns holds the columns for the "processed_donates" table.
	ProcessedDonatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "display_name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeInt64},
		{Name: "amount", Type: field.TypeInt64},
		{Name: "currency", Type: field.TypeString},
	}
	// ProcessedDonatesTable holds the schema information for the "processed_donates" table.
	ProcessedDonatesTable = &schema.Table{
		Name:       "processed_donates",
		Columns:    ProcessedDonatesColumns,
		PrimaryKey: []*schema.Column{ProcessedDonatesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProcessedDonatesTable,
	}
)

func init() {
}
