// Code generated by ent, DO NOT EDIT.

package ent

import (
	"DonateNotifier/ent/predicate"
	"DonateNotifier/ent/processeddonate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProcessedDonateDelete is the builder for deleting a ProcessedDonate entity.
type ProcessedDonateDelete struct {
	config
	hooks    []Hook
	mutation *ProcessedDonateMutation
}

// Where appends a list predicates to the ProcessedDonateDelete builder.
func (pdd *ProcessedDonateDelete) Where(ps ...predicate.ProcessedDonate) *ProcessedDonateDelete {
	pdd.mutation.Where(ps...)
	return pdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pdd *ProcessedDonateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pdd.sqlExec, pdd.mutation, pdd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pdd *ProcessedDonateDelete) ExecX(ctx context.Context) int {
	n, err := pdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pdd *ProcessedDonateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(processeddonate.Table, sqlgraph.NewFieldSpec(processeddonate.FieldID, field.TypeString))
	if ps := pdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pdd.mutation.done = true
	return affected, err
}

// ProcessedDonateDeleteOne is the builder for deleting a single ProcessedDonate entity.
type ProcessedDonateDeleteOne struct {
	pdd *ProcessedDonateDelete
}

// Where appends a list predicates to the ProcessedDonateDelete builder.
func (pddo *ProcessedDonateDeleteOne) Where(ps ...predicate.ProcessedDonate) *ProcessedDonateDeleteOne {
	pddo.pdd.mutation.Where(ps...)
	return pddo
}

// Exec executes the deletion query.
func (pddo *ProcessedDonateDeleteOne) Exec(ctx context.Context) error {
	n, err := pddo.pdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{processeddonate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pddo *ProcessedDonateDeleteOne) ExecX(ctx context.Context) {
	if err := pddo.Exec(ctx); err != nil {
		panic(err)
	}
}
