// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ProcessedDonate is the predicate function for processeddonate builders.
type ProcessedDonate func(*sql.Selector)
